version: 2
jobs:
  build:
    branches:
      ignore:
        - develop
        - /feature-.*/
    docker:
      - image: circleci/node:11.9.0
      
    steps:
      - checkout

      - run:  npm i -g firebase-tools

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: echo $SERVICE_ACCOUNT | base64 --decode > /home/circleci/project/serviceAccountKey.json
      - run: echo $ENV | base64 --decode > /home/circleci/project/env.json
      - run: npm run build:ssr 
      - run: npm run build
      - run: npm run firebse-hosting-deploy 